# Generated by Django 3.1.7 on 2022-02-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', 'insert_name_agency_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='actual_year',
            field=models.IntegerField(null=True, verbose_name='актуальный год'),
        ),
    ]
