# Generated by Django 3.1.7 on 2022-03-28 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, verbose_name='название')),
                ('id_ogr', models.IntegerField(null=True, verbose_name='id организации')),
                ('inn', models.BigIntegerField(null=True, verbose_name='инн организации')),
                ('actual_year', models.IntegerField(null=True, verbose_name='актуальный год')),
                ('url_pars', models.URLField(null=True, verbose_name='урл_для парсинга')),
                ('publishDate', models.IntegerField(null=True, verbose_name='время публикации')),
                ('url_doc', models.URLField(null=True, verbose_name='Ссылка на актуальный документ')),
                ('update_status', models.CharField(max_length=200, null=True, verbose_name='состояние обновления')),
            ],
        ),
    ]
