# Generated by Django 3.1.7 on 2022-02-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_bb_actual_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='publishDate',
            field=models.IntegerField(null=True, verbose_name='время публикации'),
        ),
        migrations.AddField(
            model_name='bb',
            name='url_doc',
            field=models.URLField(null=True, verbose_name='Ссылка на актуальный документ'),
        ),
        migrations.AddField(
            model_name='bb',
            name='url_pars',
            field=models.URLField(null=True, verbose_name='урл_для парсинга'),
        ),
    ]
