# Generated by Django 3.1.7 on 2022-04-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_auto_20220329_0046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='publishDate',
            field=models.BigIntegerField(null=True, verbose_name='время публикации'),
        ),
    ]
