# Generated by Django 3.1.7 on 2022-02-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_auto_20220205_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='update_status',
            field=models.CharField(max_length=200, null=True, verbose_name='состояние обновления'),
        ),
    ]
